modLoader = "javafml"
loaderVersion = "[25,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "drownedless"
version = "${version}"
displayName = "Drownedless"
authors = "Dialingspoon"
description = '''
Makes drowned not spawn with sky access.
'''
#logoFile = ""

[[dependencies.drownedless]]
modId = "forge"
mandatory = true
versionRange = "[25,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drownedless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.13,)"
ordering = "NONE"
side = "BOTH"
